MatrixFieldDefinition:
    type: object
    config:
        fields:
            settings:
                type: MatrixFieldDefinitionSettings
                resolve: "@=value.getFieldSettings()"

MatrixFieldDefinitionSettings:
    type: object
    config:
        fields:
            columns:
                type: "[MatrixFieldDefinitionColumn]"
            minimumRows:
                type: "Int"

MatrixFieldDefinitionColumn:
    type: object
    config:
        fields:
            name:
                type: String
            identifier:
                type: String